FROM zewo/docker:0.2.1

ENV APP_NAME=zewo.io
ENV BUILD_CONFIGURATION=debug

WORKDIR /$APP_NAME/

ADD Package.swift /$APP_NAME/
ADD Sources /$APP_NAME/Sources
ADD public /$APP_NAME/public

RUN swift build -c $BUILD_CONFIGURATION

EXPOSE 8080

CMD /$APP_NAME/.build/$BUILD_CONFIGURATION/$APP_NAME